### ISSUE TITLE
Impossible type assertion

### ISSUE THREAD

**Issue by nickng** [nickng/dingo-hunter#1]
Build fails on the latest go release (go1.5.3) with the following error:
    sesstype/sesstype.go:37: impossible type assertion:
    	*"golang.org/x/tools/go/types".Chan does not implement "go/types".Type (wrong type for Underlying method)
    		have Underlying() "golang.org/x/tools/go/types".Type
    		want Underlying() "go/types".Type

The reason seems to be https://github.com/golang/tools/commit/542ffc7e75cf45ac7ad456664a710cd96338fda6

Temporarily workaround (before go1.6 release) is to build with go1.5
